### PR TITLE
fixed telemetry reporter

### PR DESCRIPTION
**Pull request by tacksterwackster**
fixed typo causing null reference exception

### CODE REVIEW

**Comment by tacksterwackster** [comment]
@aleitner will you include this in #197? :dagger:

**Comment by tacksterwackster** [comment]
fixing this issue uncovered another issue in the `myspeed` package:

```
storjshare-0 Uncaught AssertionError: null == true
storjshare-0     at <error: TypeError: Cannot read property 'name' of undefined>
storjshare-0     at <error: TypeError: Cannot read property 'name' of undefined>
storjshare-0     at <error: TypeError: Cannot read property 'name' of undefined>
storjshare-0     at <error: TypeError: Cannot read property 'name' of undefined>
storjshare-0     at <error: TypeError: Cannot read property 'name' of undefined>
storjshare-0     at <error: TypeError: Cannot read property 'name' of undefined>
storjshare-0     at <error: TypeError: Cannot read property 'name' of undefined>
storjshare-0 ----------------------------------------
storjshare-0     at EventEmitter.on
storjshare-0     at makeWrappedCallback (/home/libby/Code/storjshare-cli/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
storjshare-0     at Socket.object.(anonymous function) [as on] (/home/libby/Code/storjshare-cli/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
storjshare-0     at Socket.Readable.on (_stream_readable.js:673:33)
storjshare-0     at tickOnSocket (_http_client.js:499:10)
storjshare-0     at onSocketNT (_http_client.js:514:5)
storjshare-0     at /home/libby/Code/storjshare-cli/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33
storjshare-0     at nextTickCallbackWith2Args (node.js:442:9)
storjshare-0     at process._tickDomainCallback (node.js:397:17)
storjshare-0     at Function.Module.runMain (module.js:443:11)
storjshare-0     at startup (node.js:139:18)
storjshare-0     at node.js:968:3
storjshare-0 ----------------------------------------
storjshare-0     at process.nextTick
storjshare-0     at makeWrappedCallback (/home/libby/Code/storjshare-cli/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
storjshare-0     at process.object.(anonymous function) [as nextTick] (/home/libby/Code/storjshare-cli/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
storjshare-0     at ClientRequest.onSocket (_http_client.js:506:11)
storjshare-0     at Agent.addRequest (_http_agent.js:144:9)
storjshare-0     at new ClientRequest (_http_client.js:142:16)
storjshare-0     at Object.exports.request (http.js:31:10)
storjshare-0     at WebSocket.initAsClient (/home/libby/Code/storjshare-cli/node_modules/myspeed/node_modules/ws/lib/WebSocket.js:708:21)
storjshare-0     at new WebSocket (/home/libby/Code/storjshare-cli/node_modules/myspeed/node_modules/ws/lib/WebSocket.js:79:18)
storjshare-0     at Client.test (/home/libby/Code/storjshare-cli/node_modules/myspeed/lib/client.js:29:27)
storjshare-0     at Object.module.exports.report (/home/libby/Code/storjshare-cli/lib/reporter.js:86:39)
storjshare-0     at open (/home/libby/Code/storjshare-cli/bin/storjshare.js:124:20)
storjshare-0     at Command.start (/home/libby/Code/storjshare-cli/bin/storjshare.js:139:7)
storjshare-0     at Command.listener (/home/libby/Code/storjshare-cli/node_modules/commander/index.js:301:8)
storjshare-0     at Command.<anonymous> (/home/libby/Code/storjshare-cli/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
storjshare-0     at emitTwo (events.js:87:13)
storjshare-0     at Command.emit (events.js:172:7)

```

**Comment by bookchin** [comment]
This is still good to merge I think, running this fork without the import of the `long-stack-traces` package functions as expected.

**Comment by aleitner** [comment]
I gotchu fam

**Pull request merged**
