### PR TITLE
Implementation dependencies.

### PR DESCRIPTION
**Pull request by MatteoCarotta**
I implemented the instruction to install dependencies npm, node, node.js

### CODE REVIEW

**Comment by littleskunk** [comment]
Please add python2 (new dependency for the last storjshare-cli update)

Could you add the $cliwininstall instruction as well?

**Comment by littleskunk** [comment]
The last line `[sudo] apt-get install nodejs` is not needed. `n lts` should install everything we need.

**Comment by MatteoCarotta** [comment]
I will update the instructions for the both of them

**Comment by littleskunk** [comment]
Windows installation step 2 and 3 need some more user action.
2.) select add python path during the installation
3.) Custom Install, Select Visual C++ during the installation

Usefull for other OS:
https://github.com/nodejs/node-gyp#installation

**Comment by gordonwritescode** [comment]
Hey d00ds, I'd really prefer if we encouraged people to use NVM to install Node.js and NPM. All of our projects come equipped already with an `.nvmrc` that specifies the supported version. You can remove a lot of installation prerequisite complexity this way as well: https://github.com/creationix/nvm#install-script

For **all** systems except for Windows:

```
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
```

Close and reopen shell *or* `source <shellprofile>` (~/.bash_profile, ~/.zshrc, ~/.profile, or ~/.bashrc), then:

```
nvm install 4.4.3
```

That will get you the correct version of Node.js and NPM. This is also a much safer way to install and run global Node programs, since NVM (which will act similar to virtualenv for python), will install global modules under `~/.nvm/...` instead of them being owned by root.

**Comment by MatteoCarotta** [comment]
Hey @gordonwritescode , it souds and looks great, especially the global ownership. I will give a try on a fresh VM.

For Windows: 
   ` nvm-windows `
or
    ``nodist``

not possible alternatives for Windows?
I don't know about the benefit of this way, maybe for future update of node stuffs....

**Comment by gordonwritescode** [comment]
@MatteoCarotta I'm not sure what the best option is for windows, I'll leave that to you and @littleskunk to decide.

**Comment by super3** [comment]
@MatteoCarotta Updates? Want to use NVM for installation. Close and then reopen a new pull when you have a NVM guide?

**Comment by bookchin** [comment]
I'm going to close this, since there hasn't been any movement. @MatteoCarotta feel free to reopen if you end up circling back.

**Pull request closed without merging**
